### ISSUE TITLE
EAP 6.0.1 domain BROKEN PIPE

### ISSUE THREAD

**Issue by alexval-es** [jitlogic/zorka#149]
Hi, I first tryed with jboss7.1.1 standalone and zorka started ok
Now I'm using: 
zorka-1.0.7
RHEL-6.4
EAP-6.0.1.zip
zabbix-2.2.6

I followed zorka configuration instrucctions for jboss7 domain mode (http://zorka.io/install/jboss7.html), and started domain.sh, then host-controller and process-controller processes started, but server instance didn't start.
On ../domain/log/process-controller.log showed java.IO.Exception BROKEN PIPE.
And ../domain/servers/as0/log/boot.log and server.log were not touched on the try.

This is not a desired configuration, but I could start ok, with only one server instance, by adding -javaagent:/path_to/zorka.jar=/path_to on JAVA_OPTS in file domain.conf. 
Zabbix is even reading data from zorka agent ;-)

Maybe is something that I'm missing after reading the instrucctions.

Please can you provide more detailed instruccions on how to configure zorca to work with jboss domain for multiple instances. 

I can make any test you need.

Thanks.

**Comment by jitlogic** [comment]
Possibly agent broke down before it was even able to start, so it crashed whole JVM process. Check console logs for server instance, maybe there are some hints. Note that com.jitlogic.zorka.core.spy package has to be added to jboss modules system classpath not only in domain controller process but also for started instances. 

I'm closing this for now (sorry it took so long), it you're still interested in solving this issue please reopen.
