### ISSUE TITLE
Feature Request: Zabbix Agent Auto registration

### ISSUE THREAD

**Issue by nucleusv** [jitlogic/zorka#164]
Hi, guys.

We have tested Zorka 1.0.13 with zabbix active checks.
It works nice, but I've tried to use Zorka for host auto registration 
https://www.zabbix.com/documentation/2.4/manual/discovery/auto_registration
and it works but it has some problems:

According  to specification 
https://www.zabbix.org/wiki/Docs/protocols/zabbix_agent/2.2

you don't send port zabbix.listen.port
in active check request 

And you don't send
HostMetadata. An optional parameter that defines host metadata. If not defined, the value will be acquired from HostMetadataItem.
So it will be great to have a new configuration parameter
zabbix.hostmetadata = "string"

{
    "host": "Host name",
    "ip": "127.0.0.1",
    "port": zabbix.listen.port,
    "host_metadata": zabbix.hostmetadata,
    "request": "active checks"
}

I very hope you will implement this, we need very much to auto-register our websphere application servers.

Thank you.

**Comment by freedba** [comment]
good, I want to need this function.

**Comment by rlewczuk** [comment]
Fixed earlier (1.0.14 AFAIR). Closing issue.
