### ISSUE TITLE
Exception in tomcat application when spring.bsh is used

### ISSUE THREAD

**Issue by borysl** [jitlogic/zorka#168]
I have installed zorka 1.0.14 to trace my application (Java-based on tomcat, spring is used)
It traced fine with tomcat, but I need extra information about how spring is being loaded.

Thus I followed this doc: http://zorka.io/install/spring.html
and added spring.bsh to my zorka.properties file.

scripts = jvm.bsh, zabbix.bsh, apache/tomcat.bsh, spring.bsh

To my surprise my application started failing for very weird reason
[zorka_log.txt](https://github.com/jitlogic/zorka/files/40170/zorka_log.txt)

I have tried to compile and run it with JDK 1.8 and JDK 1.7

The same happens when I add any of bsh script (I have tried also javax.bsh)

Please help

**Comment by rlewczuk** [comment]
You propably use spring 4.x and in fact spring.bsh script contains some errors regarding spring 4. Unfortunately I ignored this issue for some time as I concluded I'd add some safety checks to agent core first. Maybe it's time to fix this one :)

**Comment by jitlogic** [comment]
Set the following setting in zorka.properties:

spring.instr.web.view.resolver = no

Or upgrade to 1.0.16.
