### ISSUE TITLE
Zico Installation does not include self zorka agent in host list

### ISSUE THREAD

**Issue by randywallace** [jitlogic/zorka#172]
Following the install steps for Zico 1.0.15, i have it running as such:
### JVM

`/opt/jdk/latest/bin/java -Dzorka.app=zico -Xms512m -Xmx2048m -XX:MaxPermSize=256m -Dlogback.configurationFile=/opt/zico-1.0.15/./logback.xml -Dzico.home.dir=/opt/zico-1.0.15/. -javaagent:/opt/zico-1.0.15/./zorka.jar=/opt/zico-1.0.15/. -jar zico.war`
### zorka.properties

```
scripts = jvm.bsh, eclipse/jetty.bsh, zico.bsh
zabbix = no    
zorka.hostname = zico.localhost    
zorka.log.spy = DEBUG    
tracer = yes    
tracer.net = yes  
tracer.net.addr = 127.0.0.1    
zorka.spy.compute.frames = yes
```
### zico.properties

```
zico.http.port = 5703
rds.file.size = 16M
rds.max.size = 2048M
rds.seg.size = 1024K
zico.security = no
auth = anonymous
```

But, I can't seem to get the ziko.localhost, for itself, to show up in the UI.  Everything seems to be working fine; the zorka and zico logs both seem to indicate that there are no issues, I just don't see anything in the UI.

Any ideas?  I'm pretty java saavy, from an ops side, and this one has me flummoxed.

**Comment by jitlogic** [comment]
This is very strange. You can try increasing log levels for spy and tracer in zorka agent. 

I'm closing this issue for now (sorry it took me so long to react), it you still are working with zorka, please reopen it.
