### ISSUE TITLE
Need the descriptions of Method Trace Metrics header

### ISSUE THREAD

**Issue by sattishv** [jitlogic/zorka#176]
Hi team,

Could you please help us in understanding the Method Trace Header names like Time,CTime, Calls, Errors, Pct.
Time - Self time spent in each method
CTime- Not sure as it shows zero always
Calls - I could see huge number of calls been measured under this metric header like 11889 so it should been the number of calls to the method because we executed only one request.
Errors - Number of errors
Pct - Percentage of time spent from the overall response time.

Could you please review and let us know whether our assumptions are correct and clarify on CTime

Thanks
Sattish.

**Comment by jitlogic** [comment]
Time - time spent in method (including method calls registered inside the metod, i.e whole subtree);
CTime - time spent in method excluding registered subtree (that is, spent either exactly in this method or in some methods that are either excluded from tracing or filtered out automatically);
Calls - number of methods noticed by tracer but not necessarily included into trace (ie. automatically filtered out); this is useful for estimating how much overhead tracer causes; if Calls > 1000000, administrator should think about some tracer tuning (that is, excluding methods that are called too often but execute quickly);
