### ISSUE TITLE
Allow path to a specific zorka.properties file in zorka agent path.

### ISSUE THREAD

**Issue by eggzie** [jitlogic/zorka#178]
On are systems we run many instances of java. Please allow passing of path to zorka.properties files in line below. That we could have one directory with a few zorka.properties files.
i.e. /opt/zorka/zorka.tomcat0.properties, /opt/zorka/zorka.tomcat0.properties,  /opt/zorka/zorka.weglocic0.properties and /opt/zorka/zorka.weglocic0.properties

`-javaagent:/opt/zorka/zorka.jar= /opt/zorka/zorka.tomcat0.properties -Djavax.management.builder.initial=weblogic.management.jmx.mbeanserv
er.WLSMBeanServerBuilder`

**Comment by jitlogic** [comment]
Note that you have not only separate configuration files but also separate log directories. I would advise creating separate home directories but without agent .jar if you want to share agent binary. 

In 1.1.1-SNAPSHOT version it is possible to use environment variables and system properties inside zorka.properties and there is some new autodetection functionality for used application server / frameworks etc. Those two things together will allow having single configuration file for all application server, yet I still recommend using separate home directories (with symbolic links for shared files). 
Documentation for new functionalities is still not available - will appear with homepage refresh in coming weeks.
