### ISSUE TITLE
Zabbix active checks done in discovery mode do not work.

### ISSUE THREAD

**Issue by dd00f** [jitlogic/zorka#179]
When I used Zorka in active mode with the Zabbix integrtion, the first round of checks to do works fine. However, when Zabbix discovers new checks to do, Zorka doesn't use them.

The root cause of the problem is in ActiveCheckQueryItem.equals which doesn't check the equality of the key string as long as the key string isn't null. Brackets are missing in the code to align the if/else conditions correctly.

I pushed a fix for it in this fork : 
https://github.com/dd00f/zorka

I also included a quick change to use hash sets to compare the list of existing active checks vs the new checks to perform to speed up execution. I had over 1000 checks to perform in my deployment.

**Comment by jitlogic** [comment]
Hi,

I've merged your changes, some new release will possibly be published soon. 

I'm sorry it took so long :) 

Regards,
rle

**Comment by jitlogic** [comment]
Released in 1.0.16.
