### ISSUE TITLE
SpyFlagsProcessor logic error?

### ISSUE THREAD

**Issue by codeno** [jitlogic/zorka#191]
SpyFlagsProcessor.java, function process,
record.put(".STAGES", error
            ? ((f | SpyLib.ON_ERROR) & ~SpyLib.ON_RETURN)
            : ((f | SpyLib.ON_RETURN) & ~SpyLib.ON_ERROR));
Here, ON_ERROR and ON_RETURN are used as bits.

ZorkaStatsCollector.java, function submit,
if (0 != ((Integer) record.get(".STAGES") & (1 << ON_RETURN))) {...
But here ON_ERROR and ON_RETURN are used as offsets.

**Comment by jitlogic** [comment]
Nasty bug it was. Fixed in 04af84a8ea3e78c3290c5806d1c4daed9d2a1c96. 

Thank you.
