### ISSUE TITLE
Can't get data from springboot acturator through jmx

### ISSUE THREAD

**Issue by kkmaslowski** [jitlogic/zorka#197]
Hi.
How can I get values from Springboot Actuator mbeans using Zorka? For example health data is available through JConsole by jmx operation 'health'. See attached screenshot. 
![Zrzut ekranu z 2021-10-21 12-51-57](https://user-images.githubusercontent.com/910243/138263429-5daedca1-fa68-4ac5-81fd-7efbe4b60a29.png)

**Comment by rlewczuk** [comment]
Hi,

If bean exposes only operations, you need to use `zorka.jmxc[]` function to call them.
